# Datos de conexión MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/Cine

# Datos de conexión Postgrees
spring.datasource.url=jdbc:postgresql://localhost:5432/Cine
spring.datasource.username=postgres
spring.datasource.password=Atletico_10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
# Ruta de la aplicación (si aplica)
springdoc.swagger-ui.path=/swagger-ui.html
# Título y descripción de la API
#springdoc.api-docs.title=Cine
#springdoc.api-docs.version=1.0.0