# Datos de conexión
spring.datasource.url=jdbc:mongodb://localhost:27017/Cine
spring.datasource.username=dgliceras@gmail.com
spring.datasource.password=Atletico_100
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
# Ruta de la aplicación (si aplica)
springdoc.swagger-ui.path=/swagger-ui.html
# Título y descripción de la API
#springdoc.api-docs.title=Cine
#springdoc.api-docs.version=1.0.0